# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Volunteering
    url: '#volunteering'
    weight: 30
  - name: Professional development
    url: '#professionaldevelopment'
    weight: 40
  - name: Skills
    url: '#skills'
    weight: 50
  - name: Qualifications
    url: '#qualifications'
    weight: 60
  - name: Selected publications
    url: '#selectedpublications'
    weight: 70
  - name: Upcoming talks
    url: '#upcomingtalks'
    weight: 80


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
